### ISSUE TITLE
还是日期的问题

### ISSUE THREAD

**Issue by AnnoyingVillager** [GuTaoZi/GuTaoZi.github.io.idle#1]
第三条一不小心写了个9月10号到8月6号，可以改一下  (/汪汪
另外原来的sustechgate被某个j8做pre讲给老师了，建议删issue直接润

**Comment by GuTaoZi** [comment]
issue发起者只能close或edit，只有仓库持有者才能delete。

**Comment by GuTaoZi** [comment]
另外，我不觉得这有什么问题。
毕竟我只是指出其中的错误，没有提供具体的修改方案，而且我持有长期有效的合法出校申请，根本不在意的（
